name: PyInstaller packages

on:
  push:
  pull_request:

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Generate PyInstaller package
      shell: bash
      run: |
        pyinstaller resolve.spec
        cp LICENSE README.md dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: resolve-${{ matrix.os }}
        path: dist/
